########################################
# To install plugins: prefix + I
# To reload tmux: prefix + r
########################################

# tpm plugins
# (not including themes)
source-file ~/.tmux/plugins.conf

# keybinds
source-file ~/.tmux/keybinds.conf

# themes (pick ONE)
# source-file ~/.tmux/themes/dracula.conf
source-file ~/.tmux/themes/everforest.conf

# initialize TPM (must be at the end)
run '~/.tmux/plugins/tpm/tpm'

