# enable mouse control
set -g mouse on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# easy config reload using r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# fast pane-switching using Meta-arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# use vi keys in copy mode
setw -g mode-keys vi

# enable visual mode in copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection

# copy to tmux buffer, which then forwards to terminal
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
