########################################
# To install plugins: prefix + I
# To reload tmux: prefix + r
########################################

# tpm plugins
# (not including themes)
source-file ~/.config/tmux/plugins.conf

# keybinds
source-file ~/.config/tmux/keybinds.conf

# themes (pick ONE)
# source-file ~/.tmux/themes/dracula.conf
source-file ~/.config/tmux/themes/everforest.conf

# set default terminal
set -g default-terminal "xterm-256color"

# enable external clipboard forwarding (OSC 52)
set -as terminal-features ",*:clipboard"

# enable truecolor
set -sa terminal-overrides ",*:Tc"
set -sa terminal-features ",xterm-256color:RGB"

# let tmux copy selections to the outside terminal clipboard via OSC 52
set -s set-clipboard external

# initialize TPM (must be at the end)
run '~/.config/tmux/plugins/tpm/tpm'
