# the dracula theme
# https://github.com/dracula/tmux
set -g @plugin 'dracula/tmux'

# show some status in the status bar
set -g @dracula-plugins "time network network-bandwidth cpu-usage gpu-usage ram-usage"

# show tmux session id on the left of the status bar
set -g @dracula-show-left-icon session

# show time and time zone in status bar
set -g @dracula-show-timezone true

